version: "3.7"
services:
  db:
    image: mariadb:10.5.10
    container_name: db
    environment:
      MYSQL_DATABASE: db_name
      MYSQL_USER: db_user
      MYSQL_PASSWORD: db_user_pass
      MYSQL_ROOT_PASSWORD: 'root_pass'

  wordpress:
    image: wordpress:php8.0-fpm-alpine
    container_name: wordpress
    links:
      - db
    volumes:
      - wp_files:/var/www/html
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: db_user
      WORDPRESS_DB_PASSWORD: db_user_pass
      WORDPRESS_DB_NAME: "db_name"

  nginx:
    image: nginx:1.20.0-alpine
    container_name: nginx
    depends_on:
      - wordpress
    restart: always
    ports:
      - 8080:80
    volumes:
      - ./nginx/conf:/etc/nginx/conf.d
      - wp_files:/var/www/html

volumes:
  wp_files:
